name: kris-routing

services:
  kris-pgrouting:
    image: pgrouting/pgrouting:17-3.5-3.7.3
    container_name: kris-routing-pgrouting
    deploy:
      resources:
        limits:
          memory: 6g
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"



