name: kris-routing

services:
  kris-pgrouting:
    image: pgrouting/pgrouting:17-3.5-3.7.3
    container_name: kris-routing-pgrouting
    deploy:
      resources:
        limits:
          memory: 7g
          cpus: '3.5'
        reservations:
          memory: 6g
          cpus: '2.5'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

volumes:
  postgres_data:



