name: Build and test Kris Routing

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: activate extensions
        run: |
          docker compose up -d
          psql \
          "postgresql://$POSTGRES_USER:$PGPASSWORD@localhost:5432/$POSTGRES_USER" \
          -c "CREATE EXTENSION postgis; CREATE EXTENSION hstore; CREATE EXTENSION pgrouting;"

