name: Build and test Kris Routing

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: instantiate db
        run: docker compose up -d
      
      - name: activate extensions
        run: |
          psql \
          "postgresql://$POSTGRES_USER:$PGPASSWORD@localhost:5432/kris" \
          -c "CREATE EXTENSION postgis; CREATE EXTENSION hstore; CREATE EXTENSION pgrouting;"

