name: Build and test Kris Routing

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      CAMEROON_PBF_URI: "https://download.geofabrik.de/africa/cameroon-latest.osm.pbf"
      YAOUNDE_BOUNDING_BOX: 10.1,3.01,13.39,6.31

    steps:
      - uses: actions/checkout@v3

      - name: Start PostgreSQL with Docker Compose
        run: docker compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U $POSTGRES_USER; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Enable PostGIS, hstore, and pgRouting extensions
        run: |
          psql \
            "postgresql://$POSTGRES_USER:$PGPASSWORD@localhost:5432/$POSTGRES_DB" \
            -c "CREATE EXTENSION IF NOT EXISTS postgis;
                CREATE EXTENSION IF NOT EXISTS hstore;
                CREATE EXTENSION IF NOT EXISTS pgrouting;"
      
      - name: Install tools
        run: |
          sudo apt install -y osm2pgsql
          sudo apt install -y osmium-tool
      
      - name: ETL Yaounde data
        run: |
          wget $CAMEROON_PBF_URI
          osmium extract -b $YAOUNDE_BOUNDING_BOX cameroon-latest.osm.pbf -o yaounde.pbf
